#!/usr/bin/env python3
"""Read-only audit for Recall module policy, proposals, tests, and version history.

入口 facade：实现位于 scripts/recall_audit/ 分层包（VER-20260903-002）。本文件只
负责把包内全部公开名字重新导出，保证 `python scripts/audit_logic_map.py ...` 的
命令行、`--json` 输出与 tests/test_audit_logic_map.py 的属性访问路径不变。
整目录部署（skill 目录符号链接或复制 scripts/）；单独拷贝本文件不再可用。
"""

from __future__ import annotations

import sys
from datetime import date  # noqa: F401  tests 经本模块访问 date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from recall_audit.constants import (  # noqa: F401
    ADR_NAME_RE,
    ADR_STATUSES,
    AGENT_ENTRY_CONFIG_DIRS,
    AGENT_PRIVATE_DIR_NAMES,
    ANGLE_PLACEHOLDER_RE,
    BACKUP_DIR_NAMES,
    CAMEL_TEST_NAME_RE,
    CANONICAL_VERSION_RE,
    CHANGE_HEADING_RE,
    CHANGE_STATUSES,
    CONFLICT_RESOLUTIONS,
    CONTROL_RE,
    COORDINATION_ROLES,
    CURRENT_CHANGE_FIELDS,
    CURRENT_CHANGE_SECTIONS,
    CURRENT_HISTORY_ROOT,
    CURRENT_POLICY_HEADERS,
    CURRENT_README_FIELDS,
    CURRENT_README_SECTIONS,
    DECISION_AUTHORITY_ID_RE,
    DECISION_AUTHORITY_STATUSES,
    DECISION_GATES,
    DECISION_RECORD_POLICIES,
    DECISION_STATES,
    DEFAULT_EXCLUDES,
    DEPENDENCY_REFERENCE_RE,
    FINAL_DECISION_STATES,
    FINAL_SEMANTIC_REVIEW_STATES,
    FORMAL_CHANGE_BLOCK_FIELDS,
    FORMAL_CHANGE_BLOCK_SECTIONS,
    FORMAL_MEANINGFUL_FIELDS,
    FORMAL_TABLE_HEADERS,
    GOVERNANCE_MODES,
    GOVERNANCE_VERIFICATION_STATES,
    HEADING_RE,
    HISTORY_ALLOWED_CHILDREN,
    HISTORY_NAME_RE,
    HISTORY_RETENTION_POLICIES,
    INTENT_ID_RE,
    INTENT_STATUSES,
    LAYERS,
    LEGACY_HISTORY_ROOTS,
    MARKDOWN_LINK_RE,
    MEMBERSHIP_STATUSES,
    MODULE_DOC_POLICIES,
    NONE_LIKE_CONTROL_VALUES,
    PARALLEL_CURRENT_RE,
    PERSONAL_OPTIONAL_CHANGE_FIELDS,
    POSITIVE_INTEGER_RE,
    README_STATUSES,
    RECALL_ROUTES,
    REQUIRED_ADR_FIELDS,
    REQUIRED_ADR_SECTIONS,
    REQUIRED_ARCHIVE_INDEX_FIELDS,
    REQUIRED_ARCHIVE_INDEX_SECTIONS,
    REQUIRED_BACKUP_FIELDS,
    REQUIRED_BACKUP_SECTIONS,
    REQUIRED_CHANGE_FIELDS,
    REQUIRED_CHANGE_FIELDS_V2,
    REQUIRED_CHANGE_FIELDS_V2_ROOT,
    REQUIRED_CHANGE_SECTIONS,
    REQUIRED_CHANGE_SECTIONS_V2,
    REQUIRED_README_FIELDS,
    REQUIRED_README_FIELDS_V2,
    REQUIRED_README_FIELDS_V2_ROOT,
    REQUIRED_README_SECTIONS,
    REQUIRED_README_SECTIONS_V2,
    REQUIRED_README_SECTIONS_V2_ROOT,
    REQUIRED_TEMP_FIELDS,
    REQUIRED_TEMP_SECTIONS,
    REQUIRED_VERSION_FIELDS,
    REQUIRED_VERSION_SECTIONS,
    REVIEW_DUE_RE,
    REVIEW_INTERVAL_RE,
    RULE_ID_RE,
    RUNTIME_DATA_DIR_NAMES,
    RUNTIME_DATA_SUFFIXES,
    RUNTIME_STATES,
    SCOPE_TYPES,
    SEMANTIC_REVIEW_STATES,
    SOURCE_SUFFIXES,
    TEMP_STATES,
    TEST_DIRECTORY_NAMES,
    TEST_LEVELS,
    TEST_NAME_RE,
    TOPIC_ID_RE,
    TRACE_TEST_RE,
    VERSION_FILENAME_RE,
    VERSION_ID_RE,
    VERSION_ID_TOKEN_RE,
    VERSION_SLUG_RE,
    VERSION_STATUSES,
)
from recall_audit.textutil import (  # noqa: F401
    actual_case_relative,
    audit_links,
    cell_link_parts,
    cell_link_target,
    change_affected_scopes,
    change_blocks,
    contains_angle_placeholder,
    control_values,
    control_values_raw,
    has_lifecycle_trigger,
    has_meaningful_value,
    inspect_markdown,
    is_immutable_decision_record_link,
    is_iso_date,
    is_none_like,
    is_scope_ancestor,
    is_within,
    markdown_section_text,
    markdown_table_headers,
    markdown_table_rows,
    normalize_authority_id,
    normalize_change_id,
    normalize_link_target,
    normalize_scope_path,
    normalize_topic_id,
    read_text,
    relationship_items,
    relative_depth,
    scope_parts,
    split_control_list,
)
from recall_audit.fsclassify import (  # noqa: F401
    is_dependency_tree_root,
    is_foreign_subtree,
    is_generated_file,
    is_nested_project_root,
    is_runtime_data_file,
    is_source_file,
    is_test_file,
    iter_directories,
    looks_like_runtime_data_directory,
)
from recall_audit.changes import (  # noqa: F401
    change_block_semantic_issues,
    change_coordination_issues,
    change_field_tier,
    change_heading_ids,
    change_index_ids,
    change_lifecycle_issues,
    governance_evidence_issues,
    review_freshness_issues,
    traceability_issues,
)
from recall_audit.semantic import (  # noqa: F401
    ModuleAudit,
    audit_module,
    path_reference_issues,
    placeholder_issues,
    semantic_issues,
)
from recall_audit.integrity import (  # noqa: F401
    active_change_ids,
    audit_current_state_integrity,
    audit_module_routes,
    audit_proposal_integrity,
)
from recall_audit.formal import (  # noqa: F401
    audit_formal_review,
    audit_test_inventory,
)
from recall_audit.archive import (  # noqa: F401
    archive_record_identity,
    audit_agent_entrypoints,
    audit_archive,
    audit_density,
    audit_index_consistency,
    audit_root_doc_coverage,
    audit_temp_working,
    find_misplaced_records,
    find_misplaced_temp_records,
    find_nonroot_current_documents,
    find_parallel_current_candidates,
    find_scattered_backup_candidates,
    registered_child_readme_paths,
    unscanned_archive_report,
)
from recall_audit.report import (  # noqa: F401
    collect_audit,
    print_text,
    strict_failure,
)
from recall_audit.cli import (  # noqa: F401
    main,
    parse_args,
)


if __name__ == "__main__":
    raise SystemExit(main())
